#!/usr/bin/env bun
/**
 * Phase 1 smoke test: BCRG → TBFF → m1-spec end-to-end.
 *
 * Creates a test project + milestone under the existing BCRG venture,
 * verifies they exist on disk, calls VentureTreeBuilder to confirm nesting,
 * then deletes the test artifacts.
 *
 * Run: bun run scripts/smoke-phase1.ts
 *
 * NOTE: this writes to the real ~/.claude/local/ventures/bcrg/ tree.
 * Cleanup runs in the finally block so partial failures still clean up.
 *
 * Slugs use the "-smoke" suffix to avoid colliding with real TBFF/m1.
 */

import { rm } from "fs/promises";
import { existsSync } from "fs";
import { join } from "path";
import { homedir } from "os";

import { ProjectStore } from "../src/store/project";
import { MilestoneStore } from "../src/store/milestone";
import { VentureTreeBuilder } from "../src/store/tree";

const VENTURES_ROOT = join(homedir(), ".claude", "local", "ventures");
const VENTURE = "bcrg";
const PROJECT = "tbff-smoke";
const MILESTONE = "m1-smoke";

const projects = new ProjectStore({ ventures_root: VENTURES_ROOT });
const milestones = new MilestoneStore({ ventures_root: VENTURES_ROOT });
const tree = new VentureTreeBuilder({ ventures_root: VENTURES_ROOT });

async function main(): Promise<void> {
  console.log(`[smoke] using ventures_root=${VENTURES_ROOT}`);

  // Verify BCRG venture exists
  const bcrgPath = join(VENTURES_ROOT, "active", "bcrg.md");
  if (!existsSync(bcrgPath)) {
    throw new Error(`BCRG venture not found at ${bcrgPath} — cannot smoke test`);
  }
  console.log(`[smoke] BCRG venture found at ${bcrgPath}`);

  try {
    // Create project
    const proj = await projects.create({
      slug: PROJECT,
      name: "TBFF Phase 1 smoke",
      venture: VENTURE,
      stage: "active",
      priority: "high",
      owner: "shawn",
      co_owners: [],
      stakeholders: [],
      milestones: [MILESTONE],
      notes: "Auto-generated by smoke-phase1.ts. Safe to delete.",
    });
    console.log(`[smoke] project created → ${proj.file_path}`);

    // Create milestone
    const ms = await milestones.create({
      slug: MILESTONE,
      name: "m1 smoke milestone",
      project: PROJECT,
      venture: VENTURE,
      stage: "active",
      priority: "high",
      target: "smoke target",
      exit_criteria: ["criterion A", "criterion B"],
      tasks: [],
    });
    console.log(`[smoke] milestone created → ${ms.file_path}`);

    // Read back via tree
    const t = await tree.build(VENTURE);
    if (!t) throw new Error("VentureTreeBuilder returned null for BCRG");
    const found = t.projects.find((p) => p.project.slug === PROJECT);
    if (!found) throw new Error(`project ${PROJECT} not in tree`);
    if (!found.milestones.find((m) => m.slug === MILESTONE)) {
      throw new Error(`milestone ${MILESTONE} not in tree under project ${PROJECT}`);
    }

    console.log("[smoke] tree round-trip OK");
    console.log(JSON.stringify(t, null, 2).split("\n").slice(0, 40).join("\n"));
    console.log("[smoke] ✓ Phase 1 smoke PASSED");
  } finally {
    // Cleanup: nuke the project tree
    const projectDir = join(VENTURES_ROOT, VENTURE, "projects", PROJECT);
    if (existsSync(projectDir)) {
      await rm(projectDir, { recursive: true, force: true });
      console.log(`[smoke] cleanup: removed ${projectDir}`);
    }
  }
}

main().catch((e) => {
  console.error("[smoke] FAILED:", e.message);
  process.exit(1);
});
